project:
  type: website
  resources:
    - googleae307a233118a545.html

website:
  title: "Matteo Paganelli"
  site-url: "https://matteo-paganelli.github.io"
  favicon: images/mp_favicon.png
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching
      - href: service.qmd
        text: Academic Service

    right:
      - icon: building
        href: "https://unimore.unifind.cineca.it/get/person/104872"
      - icon: linkedin
        href: "https://www.linkedin.com/in/matteo-paganelli-71410a150/"
      - icon: envelope
        href: "mailto:matteo.paganelli@unimore.it"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



